{{- range $key, $job := .Values.jobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "trello-helper.fullname" $ }}-{{ $job.name }}
  labels:
    {{- include "trello-helper.labels" $ | nindent 4 }}
spec:
  schedule: {{ $job.schedule | quote }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          {{- with $.Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "trello-helper.selectorLabels" $ | nindent 12 }}
        spec:
          {{- with $.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: Never
          containers:
            - name: {{ $.Chart.Name }}
              envFrom:
                - secretRef:
                    name: {{ template "trello-helper.fullname" $ }}
              args:
                - {{ $job.command | quote }}
                - "--appKey=$(APP_KEY)"
                - "--token=$(TOKEN)"
                {{- if $job.board }}
                - "--board={{ $job.board }}"
                {{- end }}
                {{- if $job.list }}
                - "--list={{ $job.list }}"
                {{- end }}
                {{- if $job.maxAge }}
                - "--maxAge={{ $job.maxAge }}"
                {{- end }}
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              resources:
                {{- toYaml $.Values.resources | nindent 16 }}
          {{- with $.Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with $.Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with $.Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
---
{{- end }}