apiVersion: v1
kind: Secret
metadata:
  name: {{ template "trello-helper.fullname" . }}
  labels:
  {{- include "trello-helper.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  APP_KEY: {{ .Values.appKey | b64enc }}
  TOKEN: {{ .Values.token | b64enc }}